services:
  templateexpress.db:
    container_name: "templateexpress-postgres"
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user123
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=db123
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: